import re

replacements = {
    "lbl_1": "Dashboard",
    "lbl_2": "Team",
    "lbl_3": "Centers",
    "lbl_4": "Inventory",
    "lbl_5": "Reports",
    "lbl_6": "Clients",
    "lbl_7": "Analytics",
    "lbl_8": "Settings",
    "lbl_11": "Team Overview",
    "lbl_12": "Delete Appointment",
    "lbl_13": "Delete Visit",
    "lbl_14": "Are you sure you want to delete this visit?",
    "lbl_15": "Delete",
    "lbl_16": "Cancel",
    "lbl_17": "Appointment Scheduled Successfully",
    "lbl_18": "Schedule Appointment",
    "lbl_19": "Date & Time Selection",
    "lbl_20": "Confirm Appointment",
    "lbl_21": "Notes (Optional)",
    "lbl_22": "Description (Optional)",
    "lbl_23": "Location (Optional)",
    "lbl_24": "Visits",
    "lbl_25": "Schedule",
    "lbl_26": "Approve",
    "lbl_27": "Reject",
    "lbl_28": "Pending",
    "lbl_29": "Completed",
    "lbl_30": "Status",
    "lbl_31": "Assign to Representative",
    "lbl_32": "Assign",
    "lbl_33": "View Details",
    "lbl_34": "More",
    "lbl_35": "Manage",
    "lbl_38": "No records found",
    "lbl_40": "Task Details",
    "lbl_41": "Daily",
    "lbl_42": "Weekly",
    "lbl_43": "Monthly",
    "lbl_44": "Custom Date Range",
    "lbl_46": "Please enable location services",
    "lbl_47": "No targets found",
    "lbl_48": "Location Notes",
    "lbl_49": "Add Note",
    "lbl_50": "Type your note...",
    "lbl_52": "Save Note",
    "lbl_53": "No notes yet",
    "lbl_54": "Record Visit",
    "lbl_55": "End Visit",
    "lbl_57": "Submit",
    "lbl_58": "Visit Submitted",
    "lbl_59": "Submit Visit",
    "lbl_60": "Write note here...",
    "lbl_61": "Are you sure?",
    "lbl_62": "This action cannot be undone",
    "lbl_63": "Yes, proceed",
    "lbl_64": "Operation successful",
    "lbl_65": "An error occurred",
    "lbl_66": "Confirm",
    "lbl_67": "Warning",
    "lbl_71": "Schedule Appointment",
    "lbl_72": "Set Date, Time and Target",
    "lbl_73": "Date",
    "lbl_74": "Time",
    "lbl_75": "Center / Client",
    "lbl_76": "Clear",
    "lbl_77": "Select Center",
    "lbl_78": "Select Client",
    "lbl_79": "Remind me before",
    "lbl_80": "Choose Center",
    "lbl_81": "Choose Client",
    "lbl_82": "Please select a target first",
    "lbl_83": "Cannot select past dates",
    "lbl_84": "Scheduled successfully",
}

with open("lib/core/localization/app_strings.dart", "r", encoding="utf-8") as f:
    content = f.read()

for lbl_key, eng_val in replacements.items():
    # Replace the mangled string with the english value
    content = re.sub(rf"static const String {lbl_key} = '[^']+';", f"static const String {lbl_key} = '{eng_val}';", content)

with open("lib/core/localization/app_strings.dart", "w", encoding="utf-8") as f:
    f.write(content)
