// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkhg0uNt8EwyV6tdrWqXCisXp5h-6sRr8',
    appId: '1:617860143409:web:baaf4903c825ca5a357810',
    messagingSenderId: '617860143409',
    projectId: 'pdos-2a11e',
    authDomain: 'pdos-2a11e.firebaseapp.com',
    storageBucket: 'pdos-2a11e.firebasestorage.app',
    measurementId: 'G-5G65XSYHG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ARTa2VuqZn4N5s03sCrjHPCOIWhUH2E',
    appId: '1:617860143409:android:27f93fd8cb7f226d357810',
    messagingSenderId: '617860143409',
    projectId: 'pdos-2a11e',
    storageBucket: 'pdos-2a11e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDie0RAxh22OaRsR8MOhjDrpH4rbV7aXS8',
    appId: '1:617860143409:ios:bf9e75918512934d357810',
    messagingSenderId: '617860143409',
    projectId: 'pdos-2a11e',
    storageBucket: 'pdos-2a11e.firebasestorage.app',
    iosBundleId: 'com.pdos.pdosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDie0RAxh22OaRsR8MOhjDrpH4rbV7aXS8',
    appId: '1:617860143409:ios:bf9e75918512934d357810',
    messagingSenderId: '617860143409',
    projectId: 'pdos-2a11e',
    storageBucket: 'pdos-2a11e.firebasestorage.app',
    iosBundleId: 'com.pdos.pdosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkhg0uNt8EwyV6tdrWqXCisXp5h-6sRr8',
    appId: '1:617860143409:web:4fecd281ed0f7085357810',
    messagingSenderId: '617860143409',
    projectId: 'pdos-2a11e',
    authDomain: 'pdos-2a11e.firebaseapp.com',
    storageBucket: 'pdos-2a11e.firebasestorage.app',
    measurementId: 'G-6ZLTB5R7D4',
  );
}
